name: Publish Firmware

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:

  test-and-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Debug
        run: cat secrets.yaml

  build-firmware:
    uses: esphome/workflows/.github/workflows/build.yml@9f6577fd37b5cf773ab1b9be929714a0dcd15661
    with:
      files: |
        kliptag32.yaml
      esphome-version: latest
      combined-name: kliptag32
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    needs:
      - build-firmware
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@9f6577fd37b5cf773ab1b9be929714a0dcd15661
    with:
      version: ${{ github.event.release.tag_name }}